# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InternalProtocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16InternalProtocol.proto\x12\x10InternalProtocol\"K\n\rDeviceConnect\x12(\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x18.InternalProtocol.Device\x12\x10\n\x08priority\x18\x02 \x01(\r\"\xee\x01\n\x15\x44\x65viceConnectResponse\x12J\n\x0cresponseType\x18\x01 \x01(\x0e\x32\x34.InternalProtocol.DeviceConnectResponse.ResponseType\"\x88\x01\n\x0cResponseType\x12\x06\n\x02OK\x10\x00\x12\x15\n\x11\x41LREADY_CONNECTED\x10\x01\x12\x18\n\x14MODULE_NOT_SUPPORTED\x10\x02\x12\x18\n\x14\x44\x45VICE_NOT_SUPPORTED\x10\x03\x12%\n!HIGHER_PRIORITY_ALREADY_CONNECTED\x10\x04\"L\n\x0c\x44\x65viceStatus\x12(\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x18.InternalProtocol.Device\x12\x12\n\nstatusData\x18\x02 \x01(\x0c\"$\n\rDeviceCommand\x12\x13\n\x0b\x63ommandData\x18\x01 \x01(\x0c\"\xde\x01\n\x06\x44\x65vice\x12/\n\x06module\x18\x01 \x01(\x0e\x32\x1f.InternalProtocol.Device.Module\x12\x12\n\ndeviceType\x18\x02 \x01(\r\x12\x12\n\ndeviceRole\x18\x03 \x01(\t\x12\x12\n\ndeviceName\x18\x04 \x01(\t\"g\n\x06Module\x12\x13\n\x0fRESERVED_MODULE\x10\x00\x12\x12\n\x0eMISSION_MODULE\x10\x01\x12\x18\n\x14\x43\x41R_ACCESSORY_MODULE\x10\x02\x12\x13\n\x0e\x45XAMPLE_MODULE\x10\xe7\x07\"\x05\x08\x03\x10\xe6\x07\x42>Z!../internal/pkg/ba_proto;ba_proto\xaa\x02\x18Google.Protobuf.ba_protob\x06proto3')



_DEVICECONNECT = DESCRIPTOR.message_types_by_name['DeviceConnect']
_DEVICECONNECTRESPONSE = DESCRIPTOR.message_types_by_name['DeviceConnectResponse']
_DEVICESTATUS = DESCRIPTOR.message_types_by_name['DeviceStatus']
_DEVICECOMMAND = DESCRIPTOR.message_types_by_name['DeviceCommand']
_DEVICE = DESCRIPTOR.message_types_by_name['Device']
_DEVICECONNECTRESPONSE_RESPONSETYPE = _DEVICECONNECTRESPONSE.enum_types_by_name['ResponseType']
_DEVICE_MODULE = _DEVICE.enum_types_by_name['Module']
DeviceConnect = _reflection.GeneratedProtocolMessageType('DeviceConnect', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECONNECT,
  '__module__' : 'InternalProtocol_pb2'
  # @@protoc_insertion_point(class_scope:InternalProtocol.DeviceConnect)
  })
_sym_db.RegisterMessage(DeviceConnect)

DeviceConnectResponse = _reflection.GeneratedProtocolMessageType('DeviceConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECONNECTRESPONSE,
  '__module__' : 'InternalProtocol_pb2'
  # @@protoc_insertion_point(class_scope:InternalProtocol.DeviceConnectResponse)
  })
_sym_db.RegisterMessage(DeviceConnectResponse)

DeviceStatus = _reflection.GeneratedProtocolMessageType('DeviceStatus', (_message.Message,), {
  'DESCRIPTOR' : _DEVICESTATUS,
  '__module__' : 'InternalProtocol_pb2'
  # @@protoc_insertion_point(class_scope:InternalProtocol.DeviceStatus)
  })
_sym_db.RegisterMessage(DeviceStatus)

DeviceCommand = _reflection.GeneratedProtocolMessageType('DeviceCommand', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECOMMAND,
  '__module__' : 'InternalProtocol_pb2'
  # @@protoc_insertion_point(class_scope:InternalProtocol.DeviceCommand)
  })
_sym_db.RegisterMessage(DeviceCommand)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'InternalProtocol_pb2'
  # @@protoc_insertion_point(class_scope:InternalProtocol.Device)
  })
_sym_db.RegisterMessage(Device)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!../internal/pkg/ba_proto;ba_proto\252\002\030Google.Protobuf.ba_proto'
  _DEVICECONNECT._serialized_start=44
  _DEVICECONNECT._serialized_end=119
  _DEVICECONNECTRESPONSE._serialized_start=122
  _DEVICECONNECTRESPONSE._serialized_end=360
  _DEVICECONNECTRESPONSE_RESPONSETYPE._serialized_start=224
  _DEVICECONNECTRESPONSE_RESPONSETYPE._serialized_end=360
  _DEVICESTATUS._serialized_start=362
  _DEVICESTATUS._serialized_end=438
  _DEVICECOMMAND._serialized_start=440
  _DEVICECOMMAND._serialized_end=476
  _DEVICE._serialized_start=479
  _DEVICE._serialized_end=701
  _DEVICE_MODULE._serialized_start=598
  _DEVICE_MODULE._serialized_end=701
# @@protoc_insertion_point(module_scope)
